#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller:  Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /docs/index

docs:
    path: /docs
    controller:  Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /docs/index
